### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by irohafox** [grabss/grabcss#8]
### Description
We need a CONTRIBUTING.md file to provide clear guidelines for contributing to our "grabcss" project.

This file should include:

- Code of conduct.
- How to report issues.
- How to submit pull requests.
- Coding standards and best practices.

### Tasks
1. Write a code of conduct.
2. Provide instructions on how to report issues.
3. Detail the process for submitting pull requests.
4. Outline coding standards and best practices.

### How to Contribute
If you are interested in taking on this task, please comment below or open a pull request with your changes.
We appreciate your help!

### Additional Information
The CONTRIBUTING.md file should be placed in the root directory of the repository.
It should be clear and concise to encourage contributions from the community.

**Comment by singhvibhanshu** [comment]
hey @irohafox can i give a try to this issue?

**Comment by irohafox** [comment]
This issue has been resolved by PR #9.
Thank you for your contribution, @singhvibhanshu!
